### ISSUE TITLE
非常好！

### ISSUE THREAD

**Issue by sanjayheaven** [MelodyFish/react-admin-template-pro#1]
难得找到同道中人。大家一起加油！互相学习！

一点建议：

可以将网站部署在 Vercel 以供参考吗？
欢迎互相关注。我的相似仓库项目 [gganbu-admin-FE](https://github.com/sanjayheaven/gganbu-admin-FE)

**Comment by MelodyFish** [comment]
这是来自于国强的假期自动回复邮件。
 
您好，您的邮件我已收到，查收后尽快给您回复。

**Comment by MelodyFish** [comment]
非常感谢您的夸奖，您是第一位给我发邮件的人。
我本人也是刚毕业，无聊之余做的东西，希望能帮助到您。
关于部署问题我会尽快解决并在文档中更新。
若有其他问题可以随时联系，另外您的项目我明天会学习一下。
谢谢！



---原始邮件---
发件人: "Huang ***@***.***&gt;
发送时间: 2022年11月16日(周三) 晚上10:59
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [MelodyFish/react-admin-template-pro] 非常好！ (Issue #1)




 
难得找到同道中人。大家一起加油！互相学习！
 
一点建议：
 
可以将网站部署在 Vercel 以供参考吗？
 欢迎互相关注。我的相似仓库项目 gganbu-admin-FE

**Comment by MelodyFish** [comment]
> 难得找到同道中人。大家一起加油！互相学习！
> 
> 一点建议：
> 
> 可以将网站部署在 Vercel 以供参考吗？ 欢迎互相关注。我的相似仓库项目 [gganbu-admin-FE](https://github.com/sanjayheaven/gganbu-admin-FE)

Hi 蛙兄~

好久不见

项目现在已部署到了Vercel，你可以在[这里](https://www.cloudshadow.xyz)进行预览

有一说一 Vercel太强大了！点赞！
